services:
  backend:
    build: ./backend
    container_name: studroom-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
      - /var/run/mysqld:/var/run/mysqld
    env_file:
      - ./backend/.env
    extra_hosts:
      - "mysql:127.0.0.1"
    networks:
      - studroom-network

  frontend:
    build: ./frontend
    container_name: studroom-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - studroom-network

networks:
  studroom-network:
    driver: bridge

volumes:
  mysql-data:
