version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: studroom-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./backend/media:/app/media
      - ./backend/static:/app/static
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "mysql:127.0.0.1"
    networks:
      - studroom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: studroom-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    volumes:
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - studroom-network

networks:
  studroom-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
