# Generated by Django 5.2 on 2025-04-24 22:11

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_favori_utilisateur_alter_chambre_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='localisation',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
