# Generated by Django 5.2 on 2025-04-25 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_chambre_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambres_images/')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.chambre')),
            ],
        ),
    ]
