# Generated by Django 5.2 on 2025-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('active', 'Active'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
