# Generated by Django 5.2 on 2025-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_annonce_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='nombre_vues',
            field=models.IntegerField(default=0),
        ),
    ]
